version: "3"
services:
  bip-db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bip_dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  bip-web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - bip-db
      - bip-redis
  bip-redis:
    image: "redis:5.0-alpine"
    volumes:
      - "redis:/data"
volumes:
  redis:
