default: &default
  adapter: postgresql
  encoding: unicode
  username: development
  password:
  pool: 5

development:
  <<: *default
  database: bip_dev
  username: development
  password: password
  host: localhost
  port: 5435

test:
  <<: *default
  database: bip_test
  password: password
  host: localhost
  port: 5435
